# Header
menu:
  首页: /
  存档: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: 109858278973317078862
gauges_analytics:
favicon: /favicon.png
twitter: howiehu
google_plus:
fb_admins:
fb_app_id:
